### ISSUE TITLE
Batch Posting Support

### ISSUE THREAD

**Issue by solvingJ** [Nastel/JESL#1]
We have a job that runs every 5 minutes and will generate a few hundred records to be posted each time around. Is it possible to post them all with one POST request?  We can generate a separate post request for each, it's just a lot more overhead.  Also, batching many records seems a pretty common use case.

**Comment by amavashev** [comment]
Hi Jerry. I don't think rest api supports batching but our Java API does -- TNT4j. We can look into supporting batching in rest as well. Did you get your data in and displayed in jkool UI?

We have a job that runs every 5 minutes and will generate a few hundred records to be posted each time around. Is it possible to post them all with one POST request? We can generate a separate post request for each, it's just a lot more overhead. Also, batching many records seems a pretty common use case.

-

**Comment by jerrywiltse** [comment]
Albert, I got started but could not finish.  Life got in the way. Circling
back this week.

However, after reading your email, I'm glad I stopped.  I was going to use
the REST API to upload data. I had looked at TNT4J, but it seemed much more
time-consuming to implement.  I also just finished migrating to Log4J and
didn't really want to start over again.

Despite that, TNT4J does seem like a perfect fit for our use case,
especially with the batching.

With that said, would it be possible to get any hands-on assistance from
your team, in the form of an hour or two of screen sharing time?  I could
walk them through our code and we could try to swap out loggers and start
getting data in?

Regards,
Jerry

Gerald R. Wiltse
jerrywiltse@gmail.com

**Comment by amavashev** [comment]
Sure we can arrange a call. Please email me with a few time frames. In general there are several options:
1) JESL (TNT4J+jKoolCloudSink) -- Java APi for high performance streaming.
2) Log4J Appender over TNT4J -- use log4j API and stream using TNT4JAppender. No thanges to the application required.
3) RESTFul -- does not support batching yet.

**Comment by jerrywiltse** [comment]
Tomorrow any time past noon eastern.
Wednesday, basically all day.

Let me know if if those don't work.

Gerald R. Wiltse
jerrywiltse@gmail.com
