### ISSUE TITLE
Simulation events being lost

### ISSUE THREAD

**Issue by jbnas** [Nastel/JESL#3]
Running the `order-process.xml` simulation, events sporatically get "lost".  The simulator sink results show the correct number of events sent, but the jKool Gateway does not received that many.  When it does happen, it is always one of the `SQL.Execute` events in the `AcceptOrder` activity (first activity in simulation). I've seen it running both a single iteration and several iterations.

This was testing the latest code from both jesl and tnt4j repositories.

**Comment by kausandr** [comment]
Test current code having HttpClient.close fixes.
