### ISSUE TITLE
Simulation not sending all tracking items (skipping some)

### ISSUE THREAD

**Issue by jbnas** [Nastel/JESL#4]
Using the custom version of order-process.xml simulation, running 5000 iterations, it appears that not all generated tracking items are streamed to jKool server.  The metrics printed at the end of the simulation run appear to show this.

Since each iteration of my custom order-process simulation generates 7 activities and 18 events, the total number of items that should be reported to jKool server should be:
```
 7 * 5000 = 35,000 activities
18 * 5000 = 90,000 events
```
The following metrics reported by simulator confirm this:
```
TrackerImpl/tracker-activities:                             35,000
TrackerImpl/tracker-events:                                 90,000
```
However, the number of items processed by the sink are:
```
SimulatedEventSink/sink-activities:                         35,000
SimulatedEventSink/sink-events:                             88,020
SimulatedEventSink/sink-skipped:                             1,980
JKCloudEventSink/sink-direct-writes:                       123,020
JKCloudEventSink/sink-sent-messages:                       123,020
```
No reason is given as to why the events are being skipped

**Comment by kausandr** [comment]
It must be filter configured for sink, like:
```properties
event.sink.factory.Filter: com.jkoolcloud.tnt4j.filters.EventLevelTimeFilter
event.sink.factory.Filter.Level: INFO
```

in that case activities/events having level lower than INFO  are skipped.

**Comment by jbnas** [comment]
Yep, that was the issue.  Thank you.
