### ISSUE TITLE
Include Access Token in every streamed message

### ISSUE THREAD

**Issue by jbnas** [Nastel/JESL#6]
Currently, the streaming access token is only sent once, when connection is established.

Request is to include the token in EVERY HTTP message sent.  Suggestion is to use the Authorization header.

This is for future use, where routing and throttling would be done by an external gateway.

**Comment by kausandr** [comment]
Every HTTP message (except `ping` sent when client gets closed) already has header `X-API-Key` having token set.

Commit: db06593fca3992a0163c9ec2cc8ae1638b0eaf06
